# UTM Information about the working area
utm_zone: "18"
utm_band: "T"

# A Point in the AB Line
# This is also the assumed starting
# of the tractor
a:
  latitude: 45.077322     # deg
  longitude: -74.911699   # deg
  altitude: 0             # m

# B Point in the AB Line
b:
  latitude: 45.075023     # deg
  longitude: -74.909846   # deg
  altitude: 0             # m

# This is the point where the tractor
# will enter the field
entry_position:
  latitude: 45.077322     # deg
  longitude: -74.911699   # deg
  altitude: 0             # m

# The buffer distance required between
# the generated paths and the boundary
headland_width: 8.0       # m

# The width of the tool's effective area
tool_width: 5.0           # m

# The boundary of the area to be covered
# This is an ORDERED (CCW) list of points
# that creates a polygon used as a bound
# All points should follow this format:
#   latitude: _____ [deg]
#   longitude: ____ [deg]
#   altitude: _____ [m]
boundary:
  points:
    - latitude: 45.077322
      longitude: -74.911699
      altitude: 0
    - latitude: 45.075023
      longitude: -74.909846
      altitude: 0
    - latitude: 45.075024
      longitude: -74.909635
      altitude: 0
    - latitude: 45.076571
      longitude: -74.908439
      altitude: 0
    - latitude: 45.078502
      longitude: -74.909999
      altitude: 0
